/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package import_and_export_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Mayar
 */
public class Data_Entery_create extends javax.swing.JPanel {

    /**
     * Creates new form Data_Entery_create
     */
    public Data_Entery_create() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mangement = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        hour = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        min = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mangement.setBackground(new java.awt.Color(0, 102, 204));
        mangement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mangement.setForeground(new java.awt.Color(255, 255, 255));
        mangement.setBorder(null);
        mangement.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(mangement, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 280, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 204, 153));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 280, 10));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Mangement Type :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 20));

        title.setBackground(new java.awt.Color(0, 102, 204));
        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setBorder(null);
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 280, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 204, 153));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 280, 10));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Title Case :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, 20));

        hour.setBackground(new java.awt.Color(0, 102, 204));
        hour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hour.setForeground(new java.awt.Color(255, 255, 255));
        hour.setBorder(null);
        hour.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 30, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 204, 153));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 280, 10));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Date & Time case :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, 20));

        id.setBackground(new java.awt.Color(0, 102, 204));
        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setBorder(null);
        id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 204, 153));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 10));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("ID Case :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 20));

        jButton2.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("Create");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 280, 40));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, 30));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, 30));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 174, -1, 30));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        day.setBackground(new java.awt.Color(0, 102, 204));
        day.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        day.setForeground(new java.awt.Color(255, 255, 255));
        day.setBorder(null);
        day.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        jPanel2.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 30, 30));

        year.setBackground(new java.awt.Color(0, 102, 204));
        year.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        year.setForeground(new java.awt.Color(255, 255, 255));
        year.setBorder(null);
        year.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 40, 30));

        month.setBackground(new java.awt.Color(0, 102, 204));
        month.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        month.setForeground(new java.awt.Color(255, 255, 255));
        month.setBorder(null);
        month.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 20, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("/");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("/");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 0));
        jLabel12.setText("Time:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 40, -1));

        min.setBackground(new java.awt.Color(0, 102, 204));
        min.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 255));
        min.setBorder(null);
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 40, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText(":");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

             String connectionURL="jdbc:sqlserver://localhost:1433;databaseName=Export_And_Import;user=admin;password=1111";
             Connection con= DriverManager.getConnection(connectionURL);
             //Statement stat=con.createStatement();
             Case Case1=new come_case(id.getText(), title.getText(), mangement.getText(), year.getText()+"/"+month.getText()+"/"+day.getText(), hour.getText()+":"+min.getText());
             String interstring="INSERT INTO CASES_ (Id_Case,Title_Case,Mangement_Tybe,Date_Cases,Time_Cases)values('"+Integer.valueOf(Case1.getId())+"','"+Case1.getTitle()+"','"+Case1.getManagement_type()+"','"+Case1.getDate()+"','"+Case1.getTime()+"')"; 
             PreparedStatement pst=con.prepareStatement(interstring);
             ResultSet rs=pst.executeQuery();
            JOptionPane.showMessageDialog(null,"Case Cearted");
            con.close();
        }
         catch(Exception e){
            
           JOptionPane.showMessageDialog(null,e.toString());
         
           }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField day;
    private javax.swing.JTextField hour;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField mangement;
    private javax.swing.JTextField min;
    private javax.swing.JTextField month;
    private javax.swing.JTextField title;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
