/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package import_and_export_system;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Panel;

/**
 *
 * @author usser
 */
public class Data_entry extends javax.swing.JFrame {

    /**
     * Creates new form Data_entry
     */
    GridBagLayout layout = new GridBagLayout();
    Data_Entry_Add Data_entry_add;
    Data_Entery_Delete Data_entery_Delete;
    Data_Entery_create Data_Entery_create;
    Data_Entery_Edite Data_Entery_Edite;
    Data_Entery_Delete Data_Entery_Delete;
    Data_Entry_assign Data_Entry_assign;

    public Data_entry() {
        initComponents();
        Data_entry_add=new Data_Entry_Add();
        Data_entery_Delete= new Data_Entery_Delete();
        Data_Entery_create =new Data_Entery_create();
        Data_Entery_Edite =new Data_Entery_Edite();
        Data_Entry_assign=new Data_Entry_assign();
        panel7.setLayout(layout);  
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        panel7.add(Data_Entery_Edite,c);
        panel7.add(Data_Entery_create,c);
        panel7.add(Data_entry_add,c);
        panel7.add(Data_entery_Delete,c);
        panel7.add(Data_Entry_assign,c);        
        Data_entry_add.setVisible(false);
        Data_entery_Delete.setVisible(false);
        Data_Entery_create.setVisible(false);
        Data_Entery_Edite.setVisible(false);
        Data_Entry_assign.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel4 = new java.awt.Panel();
        panel7 = new java.awt.Panel();
        panel5 = new java.awt.Panel();
        panel6 = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));
        setMinimumSize(new java.awt.Dimension(993, 440));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(993, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel4.setBackground(new java.awt.Color(0, 102, 204));
        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel7.setBackground(new java.awt.Color(0, 102, 204));
        panel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel4.add(panel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 790, 380));

        panel5.setBackground(new java.awt.Color(0, 102, 204));
        panel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel5MousePressed(evt);
            }
        });
        panel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel5MouseDragged(evt);
            }
        });
        panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel4.add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 10));

        panel6.setBackground(new java.awt.Color(0, 102, 204));
        panel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Create");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 200, 60));

        jButton5.setBackground(new java.awt.Color(0, 102, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 153, 0));
        jButton5.setText("Delete");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, 60));

        jButton6.setBackground(new java.awt.Color(0, 102, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 153, 0));
        jButton6.setText("Edit");
        jButton6.setAlignmentY(0.0F);
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 210, 60));

        jButton7.setBackground(new java.awt.Color(0, 102, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 153, 0));
        jButton7.setText("Add");
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setIconTextGap(0);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText(" Cases setting");
        panel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 150, 30));

        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        panel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, 10));
        panel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        panel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        panel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 10, 40));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel6.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 10, 40));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 10, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText(" Manger setting");
        panel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        panel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 10));
        panel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel6.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 10, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("assign");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 60));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel6.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 10, 40));
        panel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Compressed\\icons\\icons8-fork-lift-24.png")); // NOI18N
        panel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 30, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Compressed\\icons\\icons8-plus-24.png")); // NOI18N
        panel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 30, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Compressed\\icons\\icons8-admin-settings-male-24 (1).png")); // NOI18N
        panel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Compressed\\icons\\icons8-edit-24 (1).png")); // NOI18N
        panel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Compressed\\icons\\icons8-delete-user-male-24.png")); // NOI18N
        panel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Compressed\\icons\\icons8-add-property-24.png")); // NOI18N
        panel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Compressed\\icons\\icons8-relay-24.png")); // NOI18N
        panel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));

        panel4.add(panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 440));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Browallia New", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 20, 20));

        jLabel10.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Export and Emport System");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 490, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -2, -1, 60));

        jLabel8.setFont(new java.awt.Font("Browallia New", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 30, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Compressed\\icons\\icons8-export-48.png")); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Compressed\\icons\\icons8-import-48.png")); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        panel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 790, 60));

        getContentPane().add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Data_Entery_Edite.setVisible(true);
        Data_entry_add.setVisible(false);
        Data_entery_Delete.setVisible(false);
        Data_Entery_create.setVisible(false);
        Data_Entry_assign.setVisible(false);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Data_entry_add.setVisible(true);
        Data_entery_Delete.setVisible(false);
        Data_Entery_create.setVisible(false);
        Data_Entery_Edite.setVisible(false);
        Data_Entry_assign.setVisible(false);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Data_Entery_create.setVisible(true);
        Data_entry_add.setVisible(false);
        Data_entery_Delete.setVisible(false);    
        Data_Entery_Edite.setVisible(false);
        Data_Entry_assign.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void panel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel5MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x, y);
        
    }//GEN-LAST:event_panel5MouseDragged

    private void panel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel5MousePressed
        // TODO add your handling code here
    }//GEN-LAST:event_panel5MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Data_entry_add.setVisible(false);
        Data_entery_Delete.setVisible(false);
        Data_Entry_assign.setVisible(true);   
        Data_Entery_create.setVisible(false);
        Data_Entery_Edite.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Data_entry_add.setVisible(false);
        Data_entery_Delete.setVisible(true);
        Data_Entry_assign.setVisible(false);   
        Data_Entery_create.setVisible(false);
        Data_Entery_Edite.setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private java.awt.Panel panel7;
    // End of variables declaration//GEN-END:variables
}
